server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
    path: /h2-console
  datasource:
    username: sa
    password:
    url: jdbc:h2:file:./data/RentFinder_db;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      springframework:
        security: TRACE