server:
  port: 8080

spring:
  datasource:
    username: your_postgresql_username
    password: your_postgresql_password
    url: jdbc:postgresql://localhost:5432/rent_finder_db  # Replace with your actual DB name and host
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      springframework:
        security: TRACE
